# Generated by Django 5.2.12 on 2026-06-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='conversation',
                    name='job_id',
                    field=models.UUIDField(blank=True, db_index=True, null=True),
                ),
            ]
        ),
        migrations.AddField(
            model_name='conversation',
            name='job_title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
