# Generated by Django 5.2.12 on 2026-04-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='s3_key',
            new_name='local_path',
        ),
    ]
