# Generated by Django 5.2.12 on 2026-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_archival_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='screening_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
