# Generated by Django 5.2.12 on 2026-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='screening_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='current_stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=30),
        ),
    ]
